general {
    disable_loading_bar = false
    hide_cursor = true
}

background {
    monitor =
    path = ~/Wallpapers
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1)

    fade_on_empty = false
    placeholder_text = <i>Pasahitza mesedez</i>

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 64

    position = 0, 100
    halign = center
    valign = center
}
