WALLPAPER_DIR="$HOME/dotfiles/Wallpapers"
WALLPAPER_IMAGE="$HOME/dotfiles/Wallpapers/dark-galaxy.1920x1080.gif"
AWWW_TRANSITION="fade"
AWWW_TRANSITION_DURATION="1"
AWWW_RESIZE="crop"
AWWW_CYCLE_SECONDS="0"
